### PR TITLE
Implemented support for custom user types in configuration

### PR DESCRIPTION
**Pull request by IgorMuzyka**
Reorganized your code a bit.
Added dependency on TypePreservingCodingAdapter to be able to use custom types with PackageConfig.
Replaced JSONSerialization with JSON Encoder/Decoder.

See for yourself.

### CODE REVIEW

**Comment by IgorMuzyka** [comment]
Fixes issue #1

**Comment by IgorMuzyka** [comment]
@orta looking forward to what you'll say about it.

**Comment by IgorMuzyka** [comment]
Now you from any library depending on `PackageConfig` developers are able to load their configuration like this:
```swift
import PackageConfig

let adapter = TypePreservingCodingAdapter()
	.register(aliased: ExampleConfiguration.self)

let example: ExampleConfiguration? = PackageConfig.load(.example, adapter: adapter)
```

**Comment by IgorMuzyka** [comment]
It's not yet working, tested with an external project which depends on `PackageConfig`.
It fails cause the `PackageConfig` when running needs to know where to find other libraries to link itself against so that types are present. Will solve this today probably.

**Comment by orta** [comment]
Nice one! Yeah, this looks great. 

This last problem is interesting, perhaps in the package.swift above you can define a which includes both PackageConfig, and the other target? then the runtime aspect of PackageConfig can guarantee those libs are either in `.build/debug` or `.build/release` 

Does look very cool though!

**Comment by IgorMuzyka** [comment]
@orta actually already solved this in a pretty nice way. Will update and push everything.

Here how the configuration inside `Package.swift` looks for my library on which i test.
Screen Shot 2019-03-16 at 19 02 01

**Comment by orta** [comment]
I love that your color scheme in Xcode-y features completely throws my intuition off, looks good!

**Pull request closed without merging**
