### PR TITLE
Now custom configuration types are supported

### PR DESCRIPTION
**Pull request by IgorMuzyka**
Now it all works.
You can define custom config types and use them within libraries and `Package.swift` (no external dependencies needed this time).
Updated readme.
@orta please check.

### CODE REVIEW

**Comment by IgorMuzyka** [comment]
Fixes #1 .

**Comment by IgorMuzyka** [comment]
Also a nice improvement is that now if multiple ther is multiple libraries using `PackageConfig` to define their config they no longer depend on `PackageConfig` in the `Package.swift` file.
```swift
#if canImport(LibraryOneConfig)
import LibraryOneConfig

LibraryOneConfig().write()
#endif 

#if can import(LibraryTwoConfig)
import LibraryTwoConfig

LibraryTwoConfig().write()
#endif
```

**Comment by IgorMuzyka** [comment]
But now there is another problem. If my package which depends on my dependency does not need `PackageConfig` then it's not in the build directory to depend on it in the first place. Will try to solve this by unmaking `PackageConfig` dynamic library(since we don't really need it as an external dependency now) and see what happens.

**Comment by orta** [comment]
You got this 👍

**Comment by IgorMuzyka** [comment]
Made it all work. Now `PackageConfig` has product `package-config` which essentially is:
```bash
mkdir -p ./Sources/PackageConfigs/
touch ./Sources/PackageConfigs/PackageConfigs.swift
swift build --target PackageConfigs
```
And user is now expected to define any dependencies that require `PackageConfig` in this target in `Package.swift`:
```swift
.target(name: "PackageConfigs", dependencies: [
    "SomeLibraryConfig",
    "package-config",
    "PackageConfig",
]),
```

What this achieves is that being present in a target assures that we get all of the dylibs of the listed libraries built when we run the executable.
So in order to use executable libraries depending on `PackageConfig` user now needs to do this:
```bash
# after adding or changing the `PackageConfigs` target
swift run resolve
# creates empty source for the target and builds it which gives us all of it's dylibs
swift run package-config

# and now user can run the dependency he wished
swift run some-executable

```


- [ ] Need to update README with all of the changes and then it's probably it if you approve.

**Comment by IgorMuzyka** [comment]
@orta pleaser review when you can. There is a lot of changes and they are definitely are breaking changes, but i think right now is just the right time to make them.

**Comment by IgorMuzyka** [comment]
Here is a my [library](https://github.com/IgorMuzyka/phase) i already updated to depend on my fork of `PackageConfig` if you want to see for yourself how it all looks/works.

**Comment by orta** [comment]
Hrm, two extra commands for all users is pretty intense. Vould they be optional and PackageConfig call them if you've not done it yet?

**Comment by IgorMuzyka** [comment]
Actually you need to run two first only once to make sure evrything is built and dylibs are available.
And  this for all of dependencies depending on `PackageConfig`.
So in ideal case it only happens when you change your dependencies depending on `PackageConfig` through `Package.swift`.
Will check if i can hide `swift package resolve` behind `swift run package-config`

**Comment by IgorMuzyka** [comment]
Done.
Now the end user of any library depending on `PackageConfig` needs to just run `swift run package-config` to ensure that all dylibs are built. This assumes that Package.swift already contains `PackageConfigs` target wrapping all of those required `Configs`.

After that user can run `swift run any-executable-depending-on-package-config` and would be able to get its config from `Package.swift` utilizing the dylibs built by `swift run package-config`.

So a correct definition in the `Package.swift` and one command to satisfy all of your dependencies with their dylibs so they can load theirs configs.

I think this way of achieving this functionality is ok.
If you have any specific ideas on how to improve further, I would gladly listen.

**Comment by IgorMuzyka** [comment]
Also considering #2 probably a nice feature for future would be to add the `var searchPaths: [String] { get }` property to `PackageConfig` protocol so that package config would link it from some more places than just `.build` directory.

**Comment by IgorMuzyka** [comment]
Ohh. Figured out another problem 😒. Can not have two or more different packages `PackageConfig` in `Package.swift` since when building for either of them they would fail with `Program used external function '_$whatever' which could not be resolved!`.
Will need to solve this somehow, not yet sure how. Since the `PackageConfig` inside the dependent library provides us with knowledge of the `dynamicLibraries` it needs there is no way currently to know another dependency `dynamicLibraries`.
A really dumb way to solve this might be just linking every possible dylib in the `.build` directory.
Note that `#if canImport(SomeConfig)` does not solve this currently.
Maybe will try to make a dylib which exports any dependency in `PackageConfigs`. and get's linked
Not sure yet.

**Comment by IgorMuzyka** [comment]
Figured out since `PackageConfig` dependent configs needs to be listed under `PackageConfigs` target to build dylibs i'll just parse `Package.swift` by hand and extract them. This way we'll link all of the dylibs required for all the `PackageConfig`s to be linked when compiling `Package.swift` with `swiftc`.

**Comment by IgorMuzyka** [comment]
It works.
Now just need to:
- [ ] Update README.md
- [ ] Update Parser

**Comment by IgorMuzyka** [comment]
@orta I think it's done.

**Comment by IgorMuzyka** [comment]
Here is [test example project](https://github.com/IgorMuzyka/package-config-test) with two of my own libraries used depending on PackageConfig from my fork.
To check how it works just run `test.sh` in the root.
It will do as follows:
```bash
rm -rf .build
rm -rf test.xcodeproj
rm -rf Package.resolved
swift run package-config
swift package generate-xcodeproj
swift run phase
swift run ignore
```

This succeeds and results in xcode project with applied changes from running executables.

**Comment by IgorMuzyka** [comment]
Hmm running `swift run package-config` fails if `PackageConfigs` target is defined but no source files for it created.
Need to mention in readme that user should run this command prior to defining `PackageConfigs` target to get the emtpy source created for him.

**Comment by orta** [comment]
( Sorry, I'm at the react native core dev summit hacking - will try get you a proper run through tomorrow. I sent you a collaborator invite too,  looks interesting  )

**Comment by IgorMuzyka** [comment]
Thats fine. Already accepted invite. Have fun at the conference.

**Comment by orta** [comment]
Alright, cool, I've given this a review - I think it all makes sense. Let's call this version 0.9.0 to give some chance to make API breaking changes in production, but I think this makes sense!

**Comment by IgorMuzyka** [comment]
Awesome 👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by IgorMuzyka** [comment]
Would you add a tag with version?)

**Comment by orta** [comment]
Shipped

Screen Shot 2019-03-24 at 8 43 00 AM

**Pull request merged**
